twitter:
  access_token: 
  access_token_secret: 
  consumer_key: 
  consumer_secret: 
aws:
  bucket_name: rongbindashboard
  aws_access_key_id: 
  aws_secret_access_key: 
company:
  company_name:
  stock:
many_company:
  company_name: APPLE,AMAZON,GOOGLE,Microsoft,Facebook,Oracle,Intel,Cisco,IBM
  stock: $APPL,$AMZN,$GOOGLE,$MSFT,$FB,$ORCL,$INTC,$CSCO,$IBM